### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by albinekb** [albinekb/playwright-single-file#1]
SingleFile is licensed under GNU, does this mean this package also has to be? Or can i just put it as standard MIT and include the GNU license in the compiled/re-distrubuted single-file-core?

Here the license/copyright is copied over when bundling:
https://github.com/albinekb/playwright-singlefile/blob/main/scripts/bundle.ts#L121-L129

Outputs:
https://github.com/albinekb/playwright-singlefile/blob/main/src/lib/vendor/single-file-bundle.js

Thanks!

**Comment by gildas-lormeau** [comment]
If you want to use a permissive MIT license, you must ensure that the single-file-cli or single-file-core files are not in your repository. This can be done, for example, by providing a build script that is responsible for downloading single-file-cli or single-file-core files and including them in your project. In this case, the user must execute this script to use your project.

Otherwise, the simplest solution is to use the GNU license. I deliberately chose AGPL because I didn't want commercial products or services to benefit from this code without compensation. I know it's restrictive, but it's more or less the only solution.

**Comment by albinekb** [comment]
Thanks for the explanation @gildas-lormeau ! I will honor that and use the same license, thanks!
